apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: procyon-dashboard-v2-treafik-ingress
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: godaddydns-procyon-letsencrypt-issuer
    k8s.kuboard.cn/displayName: procyon-dashboard-v2-treafik
    k8s.kuboard.cn/workload: procyon-dashboard-v2-treafik
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-http-redirect-https@kubernetescrd,
                                                      kube-system-http-redirect-https-testing@kubernetescrd,
                                                      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - '*.procyon.vip'
        - procyon.vip
      secretName: procyon-vip-tls
  rules:
    - host: dashboard.procyon.vip
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: procyon-dashboard-v2
              servicePort: 80
    - host: procdashboard.npool.top
      http: *http_rules
