apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-dashboard-v3-treafik-ingress
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: alidns-npool-letsencrypt-issuer
    k8s.kuboard.cn/displayName: app-dashboard-v3-treafik
    k8s.kuboard.cn/workload: app-dashboard-v3-treafik
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-http-redirect-https@kubernetescrd,
                                                      kube-system-http-redirect-https-testing@kubernetescrd,
                                                      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - '*.npool.top'
        - npool.top
      secretName: npool-top-tls
  rules:
    - host: dashboard.npool.top
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: app-dashboard-v3
              servicePort: 80
